version: '3.8'

services:
  localstack:
    image: localstack/localstack:latest
    container_name: localstack_dynamic_orch
    ports:
      - "4566:4566"
      - "4571:4571"
    environment:
      - SERVICES=s3,dynamodb
      - DEBUG=1
      - DATA_DIR=/tmp/localstack/data
